# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: git@github.com:astral-sh/ruff-pre-commit.git
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
